### ISSUE TITLE
dataloader error in run_ytb.sh

### ISSUE THREAD

**Issue by suruoxi** [HuaijiaLin/AGSS-VOS#2]
I run into a NoneType error with run_ytb.sh
 
```bash
Traceback (most recent call last):
  File "train_ytv.py", line 337, in <module>
    main()
  File "train_ytv.py", line 185, in main
    for i_iter, batch in enumerate(trainloader):
  File "/home/futian.zp/env/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/futian.zp/env/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/futian.zp/env/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/futian.zp/env/anaconda3/envs/torch0.4.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/futian.zp/cnns/AGSS-VOS/dataset/vos.py", line 172, in __getitem__
    label_cat.append(labels[i][np.newaxis,:])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by HuaijiaLin** [comment]
@suruoxi 
Do you download the 'Split_Annotatoins' directory and put it in the correct path, as mentioned in https://github.com/HuaijiaLin/AGSS-VOS#data-preparation?
